### ISSUE TITLE
APK解析失败

### ISSUE THREAD

**Issue by EtpIus** [WangXiaopai595/hafu#1]
dns可以正常拉取信息，APK文件下载后安装过程中显示解析失败

**Comment by WangXiaopai595** [comment]
可能是git的问题，我之前从git下载也是这个问题   你去盘里下载apk   替换服务器apk源文件

https://www.123pan.com/s/tinSVv-2aVsh.html

里面有个工装模式纯净版   下载重命名替换就好了

**Comment by WangXiaopai595** [comment]
车机可能要重启一下  要不然可能不会重新下载

**Comment by EtpIus** [comment]
问题已经解决，找到了其他apk文件，还有下载链接可通过迅雷或浏览器获取，感谢！
